name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      date:
        description: "스프린트 시작일 (MMDD 형식)"
        required: true
        type: string

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Create release branch
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout -b release/${{ inputs.date }}-sprint
        git commit --allow-empty -m "release/${{ inputs.date }}-sprint"
        git push origin release/${{ inputs.date }}-sprint
    - name: Create release PR
      uses: peter-evans/create-pull-request@v6
      with:
        base: main # PR의 대상 브랜치
        token: ${{ secrets.GH_TOKEN }}
        commit-message: release/${{ inputs.date }}-sprint
        title: release/${{ inputs.date }}-sprint
        body: ../pr_template.md
        branch: release/${{ inputs.date }}-sprint # PR을 생성할 브랜치 이름
